name: Unit Test
on:
  push:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: asnowc/actions@setup-node/v2
        with:
          node_v: ${{matrix.node-version}}
          pnpm_v: 9
          run_install: true
      - name: build
        run: pnpm ci:build
      - name: Unit test
        run: pnpm ci:test
